-- Independent of Step 1 / 2 / 3.
-- Unmapped URLs after smart_vdp_logic_2 matching.

CREATE TABLE IF NOT EXISTS public.smart_exception_data (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id text NOT NULL,
  urls text NOT NULL,
  cms text,
  dealer_name text,
  page_path text NOT NULL,
  views bigint NOT NULL DEFAULT 0,
  last_seen date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT smart_exception_data_customer_path_key UNIQUE (customer_id, page_path)
);

COMMENT ON TABLE public.smart_exception_data IS
  'URLs that remain Unknown/Other after standalone vdp_logic_2 cleanup. Not used by Step 1/2/3.';

CREATE INDEX IF NOT EXISTS idx_smart_exception_data_customer
  ON public.smart_exception_data (customer_id);
CREATE INDEX IF NOT EXISTS idx_smart_exception_data_cms
  ON public.smart_exception_data (cms);
CREATE INDEX IF NOT EXISTS idx_smart_exception_data_last_seen
  ON public.smart_exception_data (last_seen);

ALTER TABLE public.smart_exception_data ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.smart_exception_data TO service_role;
GRANT SELECT ON public.smart_exception_data TO authenticated;

CREATE OR REPLACE FUNCTION public.logic2_slugify(p text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT NULLIF(
    trim(both '-' FROM regexp_replace(lower(COALESCE(p, '')), '[^a-z0-9]+', '-', 'g')),
    ''
  );
$$;

CREATE OR REPLACE FUNCTION public.apply_logic2_unknown_cleanup(
  p_client_id text,
  p_from date,
  p_to date
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id text := btrim(p_client_id);
  v_logic text;
  v_cms text;
  v_name text;
  v_site text;
  v_matched int := 0;
  v_filled_make int := 0;
  v_filled_model int := 0;
  v_filled_type int := 0;
  v_exceptions int := 0;
  v_cleared int := 0;
BEGIN
  IF v_id IS NULL OR v_id = '' OR p_from IS NULL OR p_to IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'bad_args');
  END IF;

  SELECT
    NULLIF(btrim(vdp_logic), ''),
    NULLIF(btrim(cms), ''),
    NULLIF(btrim(dealer_name), ''),
    NULLIF(btrim(website_url), '')
  INTO v_logic, v_cms, v_name, v_site
  FROM public.smart_vdp_logic_2
  WHERE dealer_id = v_id
  LIMIT 1;

  IF v_name IS NULL THEN
    SELECT MIN(account_name) INTO v_name
    FROM public.smart_final_data
    WHERE client_id = v_id
      AND report_date BETWEEN p_from AND p_to;
  END IF;

  CREATE TEMP TABLE tmp_unk_paths (
    page_path text PRIMARY KEY,
    page_location text,
    views bigint
  ) ON COMMIT DROP;

  INSERT INTO tmp_unk_paths (page_path, page_location, views)
  SELECT
    f.page_path,
    MAX(NULLIF(btrim(f.page_location), '')) AS page_location,
    SUM(COALESCE(f.views, 0))::bigint AS views
  FROM public.smart_final_data f
  WHERE f.client_id = v_id
    AND f.report_date BETWEEN p_from AND p_to
    AND f.page_path IS NOT NULL
    AND btrim(f.page_path) <> ''
    AND (
      NULLIF(btrim(f.inv_url), '') IS NULL
      OR f.vdp_conditions IS DISTINCT FROM TRUE
      OR NULLIF(btrim(f.inv_make), '') IS NULL
      OR lower(btrim(f.inv_make)) IN ('unknown', 'other')
    )
  GROUP BY f.page_path;

  CREATE TEMP TABLE tmp_matched (
    page_path text PRIMARY KEY,
    page_location text
  ) ON COMMIT DROP;

  IF v_logic IS NOT NULL THEN
    INSERT INTO tmp_matched (page_path, page_location)
    SELECT u.page_path, u.page_location
    FROM tmp_unk_paths u
    WHERE public.page_path_matches_vdp_logic(u.page_path, v_logic);

    UPDATE public.smart_final_data f
    SET
      vdp_conditions = TRUE,
      inv_url = COALESCE(
        NULLIF(btrim(f.inv_url), ''),
        NULLIF(btrim(f.page_location), ''),
        CASE
          WHEN v_site IS NOT NULL THEN
            rtrim(v_site, '/') || CASE
              WHEN left(f.page_path, 1) = '/' THEN f.page_path
              ELSE '/' || f.page_path
            END
          ELSE f.page_path
        END
      ),
      inv_condition = CASE
        WHEN NULLIF(btrim(f.inv_condition), '') IS NULL
          OR lower(btrim(f.inv_condition)) IN ('unknown', 'other')
        THEN
          CASE
            WHEN f.page_path ~* '/(new)(/|$)' THEN 'New'
            WHEN f.page_path ~* '/(used|pre-owned|preowned)(/|$)' THEN 'Used'
            ELSE f.inv_condition
          END
        ELSE f.inv_condition
      END,
      inv_year = CASE
        WHEN NULLIF(btrim(f.inv_year), '') IS NULL OR btrim(f.inv_year) = '0'
        THEN COALESCE(
          (regexp_match(f.page_path, '(?:^|/)((?:19|20)[0-9]{2})(?:-|/)'))[1],
          f.inv_year
        )
        ELSE f.inv_year
      END
    WHERE f.client_id = v_id
      AND f.report_date BETWEEN p_from AND p_to
      AND f.page_path IN (SELECT page_path FROM tmp_matched);

    GET DIAGNOSTICS v_matched = ROW_COUNT;

    IF v_cms IS NOT NULL THEN
      UPDATE public.smart_final_data f
      SET inv_make = best.make
      FROM (
        SELECT DISTINCT ON (mth.page_path)
          mth.page_path,
          mk.make
        FROM tmp_matched mth
        JOIN public.smart_make mk
          ON lower(mk.cms) = lower(v_cms)
        WHERE public.logic2_slugify(mk.make) IS NOT NULL
          AND position(
            '-' || public.logic2_slugify(mk.make) || '-'
            IN '-' || COALESCE(public.logic2_slugify(mth.page_path), '') || '-'
          ) > 0
        ORDER BY mth.page_path, length(public.logic2_slugify(mk.make)) DESC
      ) best
      WHERE f.client_id = v_id
        AND f.report_date BETWEEN p_from AND p_to
        AND f.page_path = best.page_path
        AND (
          NULLIF(btrim(f.inv_make), '') IS NULL
          OR lower(btrim(f.inv_make)) IN ('unknown', 'other')
        );
      GET DIAGNOSTICS v_filled_make = ROW_COUNT;

      UPDATE public.smart_final_data f
      SET inv_model = best.model
      FROM (
        SELECT DISTINCT ON (mth.page_path)
          mth.page_path,
          md.model
        FROM tmp_matched mth
        JOIN public.smart_models md
          ON lower(md.cms) = lower(v_cms)
        WHERE public.logic2_slugify(md.model) IS NOT NULL
          AND length(public.logic2_slugify(md.model)) >= 3
          AND position(
            '-' || public.logic2_slugify(md.model) || '-'
            IN '-' || COALESCE(public.logic2_slugify(mth.page_path), '') || '-'
          ) > 0
        ORDER BY mth.page_path, length(public.logic2_slugify(md.model)) DESC
      ) best
      WHERE f.client_id = v_id
        AND f.report_date BETWEEN p_from AND p_to
        AND f.page_path = best.page_path
        AND NULLIF(btrim(f.inv_model), '') IS NULL;
      GET DIAGNOSTICS v_filled_model = ROW_COUNT;

      UPDATE public.smart_final_data f
      SET
        inv_type = c.type,
        inv_custom_type = COALESCE(NULLIF(btrim(f.inv_custom_type), ''), c.type)
      FROM public.smart_custom_unknown_fillers c
      WHERE f.client_id = v_id
        AND f.report_date BETWEEN p_from AND p_to
        AND f.page_path IN (SELECT page_path FROM tmp_matched)
        AND lower(c.cms) = lower(v_cms)
        AND lower(btrim(f.inv_make)) = lower(btrim(c.make))
        AND (
          lower(btrim(COALESCE(f.inv_model, ''))) = lower(btrim(c.model))
          OR lower(btrim(COALESCE(f.inv_model, ''))) LIKE lower(btrim(c.model)) || ' %'
        )
        AND (
          NULLIF(btrim(f.inv_type), '') IS NULL
          OR lower(btrim(f.inv_type)) IN ('unknown', 'other')
        );
      GET DIAGNOSTICS v_filled_type = ROW_COUNT;
    END IF;
  END IF;

  INSERT INTO public.smart_exception_data (
    customer_id, urls, cms, dealer_name, page_path, views, last_seen, updated_at
  )
  SELECT
    v_id,
    COALESCE(
      NULLIF(btrim(u.page_location), ''),
      CASE
        WHEN v_site IS NOT NULL THEN
          rtrim(v_site, '/') || CASE
            WHEN left(u.page_path, 1) = '/' THEN u.page_path
            ELSE '/' || u.page_path
          END
        ELSE u.page_path
      END
    ),
    v_cms,
    COALESCE(v_name, v_id),
    u.page_path,
    u.views,
    CURRENT_DATE,
    now()
  FROM tmp_unk_paths u
  WHERE NOT EXISTS (
    SELECT 1 FROM tmp_matched m WHERE m.page_path = u.page_path
  )
  ON CONFLICT (customer_id, page_path)
  DO UPDATE SET
    urls = EXCLUDED.urls,
    cms = COALESCE(EXCLUDED.cms, public.smart_exception_data.cms),
    dealer_name = COALESCE(EXCLUDED.dealer_name, public.smart_exception_data.dealer_name),
    views = EXCLUDED.views,
    last_seen = EXCLUDED.last_seen,
    updated_at = now();

  GET DIAGNOSTICS v_exceptions = ROW_COUNT;

  DELETE FROM public.smart_exception_data e
  WHERE e.customer_id = v_id
    AND (
      e.page_path IN (SELECT page_path FROM tmp_matched)
      OR NOT EXISTS (
        SELECT 1 FROM tmp_unk_paths u WHERE u.page_path = e.page_path
      )
    );
  GET DIAGNOSTICS v_cleared = ROW_COUNT;

  RETURN jsonb_build_object(
    'ok', true,
    'client_id', v_id,
    'dealer_name', v_name,
    'cms', v_cms,
    'has_logic2', v_logic IS NOT NULL,
    'unknown_paths', (SELECT COUNT(*) FROM tmp_unk_paths),
    'mapped_rows', v_matched,
    'filled_make_rows', v_filled_make,
    'filled_model_rows', v_filled_model,
    'filled_type_rows', v_filled_type,
    'exception_paths', v_exceptions,
    'cleared_exceptions', v_cleared
  );
END;
$$;

COMMENT ON FUNCTION public.apply_logic2_unknown_cleanup(text, date, date) IS
  'Standalone Unknown/Other cleanup using smart_vdp_logic_2. Writes leftovers to smart_exception_data. Does not run Step 1/2/3.';

REVOKE ALL ON FUNCTION public.apply_logic2_unknown_cleanup(text, date, date) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_logic2_unknown_cleanup(text, date, date)
  TO service_role;

REVOKE ALL ON FUNCTION public.logic2_slugify(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.logic2_slugify(text) TO service_role;
