-- Master dealer locations (separate from smart_final_data.inv_location).
-- Used by get_dealer_location_breakdown only — does not change existing RPCs.
-- Run in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS public.smart_dealer_locations (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id        text NOT NULL,
  dealer_name      text,
  location_number  text,
  location_name    text NOT NULL,
  inv_match_value  text NOT NULL,
  page_match_value text,
  sort_order       integer NOT NULL DEFAULT 0,
  is_active        boolean NOT NULL DEFAULT true,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT smart_dealer_locations_client_match_unique
    UNIQUE (client_id, inv_match_value)
);

CREATE INDEX IF NOT EXISTS idx_dealer_locations_client_active
  ON public.smart_dealer_locations (client_id, is_active, sort_order);

COMMENT ON TABLE public.smart_dealer_locations IS
  'Configured store locations per dealer. Location donut uses this table; other breakdowns still use smart_final_data.inv_location.';

COMMENT ON COLUMN public.smart_dealer_locations.location_number IS
  'Optional store # shown with name (e.g. 101).';

COMMENT ON COLUMN public.smart_dealer_locations.location_name IS
  'Display label in Location Breakdown donut.';

COMMENT ON COLUMN public.smart_dealer_locations.inv_match_value IS
  'Matches smart_final_data.inv_location (trimmed). Used by VDP filters and page-to-location join.';

COMMENT ON COLUMN public.smart_dealer_locations.page_match_value IS
  'Optional substring/path match on smart_ga4_page_data.page_location or page_path. Falls back to inv_match_value.';

-- If table already exists without page_match_value:
-- ALTER TABLE public.smart_dealer_locations ADD COLUMN IF NOT EXISTS page_match_value text;

-- Optional one-time backfill from existing final data (review before running):
--
-- INSERT INTO public.smart_dealer_locations (
--   client_id, dealer_name, location_number, location_name, inv_match_value, sort_order
-- )
-- SELECT
--   f.client_id,
--   MAX(f.account_name),
--   NULL,
--   TRIM(f.inv_location),
--   TRIM(f.inv_location),
--   ROW_NUMBER() OVER (PARTITION BY f.client_id ORDER BY TRIM(f.inv_location))::int
-- FROM public.smart_final_data f
-- WHERE f.inv_location IS NOT NULL
--   AND TRIM(f.inv_location) <> ''
-- GROUP BY f.client_id, TRIM(f.inv_location)
-- ON CONFLICT (client_id, inv_match_value) DO NOTHING;
